# Generated by Django 2.2 on 2020-09-05 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20200905_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='upvote',
            field=models.ManyToManyField(related_name='Upvote_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
