# Generated by Django 2.2 on 2020-09-05 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20200905_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='Upvote_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qnatags',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
