# Generated by Django 2.2 on 2020-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200829_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='security_ans',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='security_qs',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='agentId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='guideId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='userId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
