# Generated by Django 2.2 on 2020-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201125_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
