# Generated by Django 2.2 on 2020-08-30 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200830_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govIdType', models.CharField(choices=[('PAN', 'PAN'), ('Adhar', 'Adhar')], max_length=10)),
                ('govIdNo', models.CharField(max_length=20)),
                ('govIdImage', models.ImageField(upload_to='GovermentId_Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userGov', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyName', models.CharField(max_length=50)),
                ('agencyPhNo', models.BigIntegerField()),
                ('agencyCountry', models.CharField(max_length=25)),
                ('agencyCity', models.CharField(max_length=20)),
                ('agencyState', models.CharField(max_length=20)),
                ('agencyZipCode', models.BigIntegerField()),
                ('govApproved', models.BooleanField(default=False)),
                ('govApprovedId', models.CharField(blank=True, max_length=20, null=True)),
                ('agencyAddress', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAgency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
