# Generated by Django 2.2 on 2020-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agencydetail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
