# Generated by Django 2.2 on 2020-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agencydetail_govid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phNo',
            field=models.BigIntegerField(),
        ),
    ]
