# Generated by Django 2.2 on 2020-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200902_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='agency_Id',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
