# Generated by Django 2.2 on 2020-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_agencydetail_agency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govid',
            name='govIdType',
            field=models.CharField(choices=[('PAN', 'PAN'), ('ADHAR', 'ADHAR')], max_length=10),
        ),
    ]
