# Generated by Django 2.2 on 2020-11-12 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_people', models.IntegerField(default=30)),
                ('tourId', models.CharField(max_length=30, unique=True)),
                ('tourHeading', models.CharField(max_length=1000)),
                ('tourSlug', models.SlugField(max_length=255, unique=True)),
                ('startingLocation', models.CharField(max_length=300)),
                ('endLocation', models.CharField(max_length=300)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('inclusive', models.TextField()),
                ('exclusive', models.TextField()),
                ('highlight', models.TextField()),
                ('price', models.FloatField()),
                ('tour_type', models.CharField(choices=[('Family Special', 'Family Special'), ('Friends Special', 'Friends Special'), ('Couple Friendly', 'Couple Friendly'), ('Solo Tour', 'Solo Tour'), ('All', 'All')], max_length=500)),
                ('thumbnail', models.ImageField(upload_to='TourAccountThumbnail')),
                ('last_booking_date', models.DateField()),
                ('last_cancel_date', models.DateField()),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('othersThings', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('nearestLocation1', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation1_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected1', models.TextField(blank=True, null=True)),
                ('nearestLocation2', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation2_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected2', models.TextField(blank=True, null=True)),
                ('nearestLocation3', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation3_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected3', models.TextField(blank=True, null=True)),
                ('nearestLocation4', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation4_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected4', models.TextField(blank=True, null=True)),
                ('publish_mode', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourAgency', to='accounts.AgencyDetail')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
