# Generated by Django 2.2 on 2020-09-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200902_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourId', models.CharField(max_length=400)),
                ('tourHeading', models.CharField(max_length=1000)),
                ('startingLocation', models.CharField(max_length=300)),
                ('endLocation', models.CharField(max_length=300)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('description', models.TextField()),
                ('inclusive', models.TextField()),
                ('exclusive', models.TextField()),
                ('highlight', models.TextField()),
                ('price', models.FloatField()),
                ('tour_type', models.CharField(choices=[('Family Special', 'Family Special'), ('Friends Special', 'Friends Special'), ('Couple Friendly', 'Couple Friendly'), ('Solo Tour', 'Solo Tour')], max_length=500)),
                ('thumbnail', models.ImageField(upload_to='TourAccountThumbnail')),
                ('othersThings', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('nearestLocation1', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation1_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected1', models.TextField(blank=True, null=True)),
                ('nearestLocation2', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation2_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected2', models.TextField(blank=True, null=True)),
                ('nearestLocation3', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation3_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected3', models.TextField(blank=True, null=True)),
                ('nearestLocation4', models.CharField(blank=True, max_length=500, null=True)),
                ('nearestLocation4_distance', models.FloatField(blank=True, null=True)),
                ('nlocationconnected4', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AgencyDetail')),
            ],
        ),
    ]
