# Generated by Django 2.2 on 2020-09-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelagency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='seller',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='agencyOwner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tourSlug',
            field=models.SlugField(default='Test', unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourAgency', to='accounts.AgencyDetail'),
        ),
    ]
