# Generated by Django 2.2 on 2020-11-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='publish_mode',
            field=models.BooleanField(default=False),
        ),
    ]
