# Generated by Django 2.2 on 2020-11-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0002_auto_20201113_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='TourPreview')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelagency.Tour')),
            ],
        ),
    ]
