# Generated by Django 2.2 on 2020-11-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0003_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tourSlug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
