# Generated by Django 2.2 on 2020-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0005_auto_20201122_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='last_cancel_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='noOfManPerRoom',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='specialOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='specialOfferDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
