# Generated by Django 2.2 on 2020-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0006_auto_20201125_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('Family-Special', 'Family-Special'), ('Friends-Special', 'Friends-Special'), ('Couple-Friendly', 'Couple-Friendly'), ('Solo-Tour', 'Solo-Tour'), ('Bike-tours', 'Bike-tours'), ('Self-drive car-tours', 'Self-drive car-tours'), ('Trecking-Special', 'Trecking-Special'), ('All', 'All')], max_length=500),
        ),
    ]
