# Generated by Django 2.2 on 2020-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0007_auto_20201126_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation1',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation1_distance',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation2',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation2_distance',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation3',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation3_distance',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation4',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearestLocation4_distance',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nlocationconnected1',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nlocationconnected2',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nlocationconnected3',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nlocationconnected4',
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(max_length=1000),
        ),
    ]
