# Generated by Django 2.2 on 2020-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0008_auto_20201128_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('Family-Special', 'Family-Special'), ('Friends-Special', 'Friends-Special'), ('Couple-Friendly', 'Couple-Friendly'), ('Solo-Tour', 'Solo-Tour'), ('All', 'All')], max_length=500),
        ),
    ]
