# Generated by Django 2.2 on 2020-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0009_auto_20201128_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='noOfManPerRoom',
        ),
        migrations.AddField(
            model_name='tour',
            name='special_tour_type',
            field=models.CharField(choices=[('Bike-tours', 'Bike-tours'), ('Self-drive', 'Self-drive'), ('Trecking-Special', 'Trecking-Special'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('Family-Special', 'Family-Special'), ('Friends-Special', 'Friends-Special'), ('Couple-Friendly', 'Couple-Friendly'), ('Solo-Tour', 'Solo-Tour'), ('All', 'All')], max_length=50),
        ),
    ]
