# Generated by Django 2.2 on 2020-12-31 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelagency', '0010_auto_20201128_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('destination_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationName', to='traveller.DestinationWishlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to=settings.AUTH_USER_MODEL)),
                ('wishedTour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelagency.Tour')),
            ],
        ),
    ]
