# Generated by Django 2.2 on 2020-12-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='destination_name',
        ),
        migrations.DeleteModel(
            name='DestinationWishlist',
        ),
    ]
