# Generated by Django 2.2 on 2020-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0002_auto_20201123_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_price',
            new_name='paid_by_user',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
