# Generated by Django 2.2 on 2020-11-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201118_1344'),
        ('travelagency', '0005_auto_20201122_1024'),
        ('touring', '0005_auto_20201123_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelled_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=600)),
                ('total_people', models.IntegerField()),
                ('paid_by_user', models.FloatField()),
                ('total_price', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cancelled_by', models.CharField(choices=[('AGENT', 'AGENT'), ('USER', 'USER')], max_length=200)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAgency', to='accounts.AgencyDetail')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAgent', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ccustomer', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CTour', to='travelagency.Tour')),
            ],
        ),
    ]
